version: "3.7"
   
services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - pgdata:/usr/src/app
    ports:
      - "8000:8000"
    environment: 
      DEBUG: 'true'

      

volumes:
  pgdata:
  web-static: